[exloli-next]
src.git = "https://github.com/lolishinshi/exloli-next"
fetch.github = "lolishinshi/exloli-next"

[geolite2-asn]
src.github = "P3TERX/GeoLite.mmdb"
fetch.url = "https://github.com/P3TERX/GeoLite.mmdb/releases/download/$ver/GeoLite2-ASN.mmdb"

[geolite2-city]
src.github = "P3TERX/GeoLite.mmdb"
fetch.url = "https://github.com/P3TERX/GeoLite.mmdb/releases/download/$ver/GeoLite2-City.mmdb"

[geolite2-country]
src.github = "P3TERX/GeoLite.mmdb"
fetch.url = "https://github.com/P3TERX/GeoLite.mmdb/releases/download/$ver/GeoLite2-Country.mmdb"

[v2ray-rules-dat-geoip]
src.github = "Loyalsoldier/v2ray-rules-dat"
fetch.url = "https://github.com/Loyalsoldier/v2ray-rules-dat/releases/download/$ver/geoip.dat"

[v2ray-rules-dat-geosite]
src.github = "Loyalsoldier/v2ray-rules-dat"
fetch.url = "https://github.com/Loyalsoldier/v2ray-rules-dat/releases/download/$ver/geosite.dat"

[libinput-three-finger-drag]
src.git = "https://github.com/marsqing/libinput-three-finger-drag"
fetch.github = "marsqing/libinput-three-finger-drag"

[english_words]
src.git = "https://github.com/dwyl/english-words.git"
fetch.github = "dwyl/english-words"

[fcitx5-themes-candlelight]
src.git = "https://github.com/thep0y/fcitx5-themes-candlelight.git"
fetch.github = "thep0y/fcitx5-themes-candlelight"

[sing-box]
src.github_tag = "SagerNet/sing-box"
fetch.github = "SagerNet/sing-box"

[dank-material-shell]
src.github_tag = "bbedward/DankMaterialShell"
fetch.github = "bbedward/DankMaterialShell"
