# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  dank-material-shell = {
    pname = "dank-material-shell";
    version = "v0.0.7";
    src = fetchFromGitHub {
      owner = "bbedward";
      repo = "DankMaterialShell";
      rev = "v0.0.7";
      fetchSubmodules = false;
      sha256 = "sha256-s2IKIbvPrhhiUkrD+CQP77LdpgWV62ARix0BC2p1UPo=";
    };
  };
  english_words = {
    pname = "english_words";
    version = "20f5cc9b3f0ccc8ce45d814c532b7c2031bba31c";
    src = fetchFromGitHub {
      owner = "dwyl";
      repo = "english-words";
      rev = "20f5cc9b3f0ccc8ce45d814c532b7c2031bba31c";
      fetchSubmodules = false;
      sha256 = "sha256-PfBQ9iavOLx7M8+j0TXASUxVamPiQn2YXsiuUmz4XCg=";
    };
    date = "2025-01-06";
  };
  exloli-next = {
    pname = "exloli-next";
    version = "41d7a6e52a1625d6febb47160a4b143ca47c16d5";
    src = fetchFromGitHub {
      owner = "lolishinshi";
      repo = "exloli-next";
      rev = "41d7a6e52a1625d6febb47160a4b143ca47c16d5";
      fetchSubmodules = false;
      sha256 = "sha256-S3hjuRSDtPkK9XF2USXfyOawWoD/fu9qYDJbUPI3Op0=";
    };
    date = "2024-11-23";
  };
  fcitx5-themes-candlelight = {
    pname = "fcitx5-themes-candlelight";
    version = "d4146d3d3f7a276a8daa2847c3e5c08de20485da";
    src = fetchFromGitHub {
      owner = "thep0y";
      repo = "fcitx5-themes-candlelight";
      rev = "d4146d3d3f7a276a8daa2847c3e5c08de20485da";
      fetchSubmodules = false;
      sha256 = "sha256-/IdN69izB30rl1gswsXivYtpAeCUdahP7oy06XJXo0I=";
    };
    date = "2024-08-03";
  };
  geolite2-asn = {
    pname = "geolite2-asn";
    version = "2025.09.19";
    src = fetchurl {
      url = "https://github.com/P3TERX/GeoLite.mmdb/releases/download/2025.09.19/GeoLite2-ASN.mmdb";
      sha256 = "sha256-XcKyiL+glMPlyoMuXnDXF0zPEJ/yjTKIwJiNc4L6zz0=";
    };
  };
  geolite2-city = {
    pname = "geolite2-city";
    version = "2025.09.19";
    src = fetchurl {
      url = "https://github.com/P3TERX/GeoLite.mmdb/releases/download/2025.09.19/GeoLite2-City.mmdb";
      sha256 = "sha256-tqu3VHhLMctrRE87EQ8v2f307Trjg9cf/vbftpciQPo=";
    };
  };
  geolite2-country = {
    pname = "geolite2-country";
    version = "2025.09.19";
    src = fetchurl {
      url = "https://github.com/P3TERX/GeoLite.mmdb/releases/download/2025.09.19/GeoLite2-Country.mmdb";
      sha256 = "sha256-v4ObP0dXknhn8eo9/XkrFrDZGgVjL/TrL0+jWMOOcUQ=";
    };
  };
  libinput-three-finger-drag = {
    pname = "libinput-three-finger-drag";
    version = "6acd3f84b551b855b5f21b08db55e95dae3305c5";
    src = fetchFromGitHub {
      owner = "marsqing";
      repo = "libinput-three-finger-drag";
      rev = "6acd3f84b551b855b5f21b08db55e95dae3305c5";
      fetchSubmodules = false;
      sha256 = "sha256-xmcTb+23d6mMzIfMVjzN6bwV0fWH4p6YhXXqrFmt4TM=";
    };
    date = "2024-06-17";
  };
  v2ray-rules-dat-geoip = {
    pname = "v2ray-rules-dat-geoip";
    version = "202509182211";
    src = fetchurl {
      url = "https://github.com/Loyalsoldier/v2ray-rules-dat/releases/download/202509182211/geoip.dat";
      sha256 = "sha256-UsVsVwL4VAEGuMvcDESPuDhE+5MDauFhALh42S7xWA0=";
    };
  };
  v2ray-rules-dat-geosite = {
    pname = "v2ray-rules-dat-geosite";
    version = "202509182211";
    src = fetchurl {
      url = "https://github.com/Loyalsoldier/v2ray-rules-dat/releases/download/202509182211/geosite.dat";
      sha256 = "sha256-8FsyJ+wPjLlRX7ETGj01riykXuU93BQBat8DEjsOGoY=";
    };
  };
}
