# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  english_words = {
    pname = "english_words";
    version = "20f5cc9b3f0ccc8ce45d814c532b7c2031bba31c";
    src = fetchFromGitHub {
      owner = "dwyl";
      repo = "english-words";
      rev = "20f5cc9b3f0ccc8ce45d814c532b7c2031bba31c";
      fetchSubmodules = false;
      sha256 = "sha256-PfBQ9iavOLx7M8+j0TXASUxVamPiQn2YXsiuUmz4XCg=";
    };
    date = "2025-01-06";
  };
  exloli-next = {
    pname = "exloli-next";
    version = "41d7a6e52a1625d6febb47160a4b143ca47c16d5";
    src = fetchFromGitHub {
      owner = "lolishinshi";
      repo = "exloli-next";
      rev = "41d7a6e52a1625d6febb47160a4b143ca47c16d5";
      fetchSubmodules = false;
      sha256 = "sha256-S3hjuRSDtPkK9XF2USXfyOawWoD/fu9qYDJbUPI3Op0=";
    };
    date = "2024-11-23";
  };
  fcitx5-themes-candlelight = {
    pname = "fcitx5-themes-candlelight";
    version = "653677b0454569f41c815b3d262a57e42c90ee05";
    src = fetchFromGitHub {
      owner = "thep0y";
      repo = "fcitx5-themes-candlelight";
      rev = "653677b0454569f41c815b3d262a57e42c90ee05";
      fetchSubmodules = false;
      sha256 = "sha256-dN77aUt1qkN177BZOfrT6O72Qp0J2jlM2mGNxI0cBnA=";
    };
    date = "2025-11-07";
  };
  flapalerted = {
    pname = "flapalerted";
    version = "64a86e9aea722ce4755ea098fd4fec44d99dcc51";
    src = fetchFromGitHub {
      owner = "Kioubit";
      repo = "FlapAlerted";
      rev = "64a86e9aea722ce4755ea098fd4fec44d99dcc51";
      fetchSubmodules = false;
      sha256 = "sha256-TD6enzFHNub6M+cabj7ywkx+ax373YLkANL12Nt5ITU=";
    };
    date = "2025-11-24";
  };
  geolite2-asn = {
    pname = "geolite2-asn";
    version = "2025.11.25";
    src = fetchurl {
      url = "https://github.com/P3TERX/GeoLite.mmdb/releases/download/2025.11.25/GeoLite2-ASN.mmdb";
      sha256 = "sha256-b01jxql/vAnvkzn5T/vTXL4XGKV/5bIf37rSYxdaqG4=";
    };
  };
  geolite2-city = {
    pname = "geolite2-city";
    version = "2025.11.25";
    src = fetchurl {
      url = "https://github.com/P3TERX/GeoLite.mmdb/releases/download/2025.11.25/GeoLite2-City.mmdb";
      sha256 = "sha256-JXiAzKSacZM+jB6XSQOd6hQjaBThtojjxn54BjIO4cA=";
    };
  };
  geolite2-country = {
    pname = "geolite2-country";
    version = "2025.11.25";
    src = fetchurl {
      url = "https://github.com/P3TERX/GeoLite.mmdb/releases/download/2025.11.25/GeoLite2-Country.mmdb";
      sha256 = "sha256-Nu6NGlLYA8Wm/qGsU3rp6ZkdxXL/VRqvAUhQB16mDAE=";
    };
  };
  libinput-three-finger-drag = {
    pname = "libinput-three-finger-drag";
    version = "6acd3f84b551b855b5f21b08db55e95dae3305c5";
    src = fetchFromGitHub {
      owner = "marsqing";
      repo = "libinput-three-finger-drag";
      rev = "6acd3f84b551b855b5f21b08db55e95dae3305c5";
      fetchSubmodules = false;
      sha256 = "sha256-xmcTb+23d6mMzIfMVjzN6bwV0fWH4p6YhXXqrFmt4TM=";
    };
    date = "2024-06-17";
  };
  pixy2 = {
    pname = "pixy2";
    version = "d7c38d49ae8071b58e46f5b35eda927dd2b7c621";
    src = fetchFromGitHub {
      owner = "charmedlabs";
      repo = "pixy2";
      rev = "d7c38d49ae8071b58e46f5b35eda927dd2b7c621";
      fetchSubmodules = false;
      sha256 = "sha256-w0t7KqV8OS3PJBdZtLn86zknQYo70rBv7fuK/UFx9zQ=";
    };
    date = "2024-07-17";
  };
  v2ray-rules-dat-geoip = {
    pname = "v2ray-rules-dat-geoip";
    version = "202511242213";
    src = fetchurl {
      url = "https://github.com/Loyalsoldier/v2ray-rules-dat/releases/download/202511242213/geoip.dat";
      sha256 = "sha256-dmaakIEbcWbcrGIdypD2JG4rIQZTwYhDVRN/QvQRUrA=";
    };
  };
  v2ray-rules-dat-geosite = {
    pname = "v2ray-rules-dat-geosite";
    version = "202511242213";
    src = fetchurl {
      url = "https://github.com/Loyalsoldier/v2ray-rules-dat/releases/download/202511242213/geosite.dat";
      sha256 = "sha256-NIplq6wHsYUy011/GZzIOjOJliGzoah+u5lT2KxGkmY=";
    };
  };
}
