name: "Prepare Nix"
description: "Setup Nix and Attic cache"
inputs:
  GH_PAT:
    description: "GitHub Personal Access Token"
    required: true
  ATTIC_TOKEN:
    description: "Token for Attic Cache"
    required: true
  ATTIC_SERVER:
    description: "Attic Server URL"
    required: true
  ATTIC_CACHE:
    description: "Attic Cache Name"
    required: true
  ONLY_NIX:
    type: boolean
    default: false

runs:
  using: "composite"
  steps:
    - name: Nothing but nix
      if: ${{ runner.os == 'Linux' && inputs.ONLY_NIX != 'true' }}
      uses: wimpysworld/nothing-but-nix@main
      with:
        hatchet-protocol: rampage
        root-safe-haven: 2048

    - name: Install nix
      uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        github_access_token: ${{ inputs.GH_PAT }}
        extra_nix_config: |
          build-dir = /nix/build
          experimental-features = nix-command flakes ca-derivations auto-allocate-uids cgroups pipe-operators dynamic-derivations recursive-nix
          system-features = nixos-test benchmark big-parallel kvm
          keep-going = false
          accept-flake-config = true
          abort-on-warn = true
          log-lines = 25
          netrc-file = /nix/secrets/nix-netrc

    - name: Prepare
      shell: bash
      env:
        ATTIC_TOKEN: ${{ inputs.ATTIC_TOKEN }}
        ATTIC_SERVER: ${{ inputs.ATTIC_SERVER }}
      run: |
        sudo mkdir -p /nix/secrets
        printf "machine nix-cache.qaq.li\npassword %s\n" "$ATTIC_TOKEN" | sudo tee /nix/secrets/nix-netrc > /dev/null
        df -h
        sudo mkdir -p /nix/build

    - name: Install packages
      shell: bash
      if: ${{ inputs.ONLY_NIX != 'true' }}
      run: |
        pkgs=(coreutils jq gnused attic-client nix-fast-build)

        extra_args=""
        if [ -f "flake.nix" ]; then
          extra_args="--inputs-from . --accept-flake-config"
        else
        fi

        nix profile add "${pkgs[@]/#/nixpkgs#}" $extra_args

    - name: Setup Attic cache
      shell: bash
      if: ${{ inputs.ONLY_NIX != 'true' }}
      run: |
        attic login default "$ATTIC_SERVER" "$ATTIC_TOKEN"
        if ! attic cache info "$ATTIC_CACHE"; then
          echo "::error::attic returned an error"
          exit 0
        fi
      env:
        ATTIC_SERVER: ${{ inputs.ATTIC_SERVER }}
        ATTIC_CACHE: ${{ inputs.ATTIC_CACHE }}
        ATTIC_TOKEN: ${{ inputs.ATTIC_TOKEN }}
